-- Create a new table for documents (PDFs, DOCs, spreadsheets, etc.)
CREATE TABLE documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  related_type TEXT NOT NULL, -- 'dog', 'litter', 'puppy'
  related_id BIGINT NOT NULL,
  url TEXT NOT NULL,
  original_filename TEXT,
  title TEXT,
  description TEXT,
  file_type TEXT NOT NULL DEFAULT 'document',
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create an index for faster lookups
CREATE INDEX idx_documents_related ON documents (related_type, related_id);

-- Disable RLS for documents table
ALTER TABLE documents DISABLE ROW LEVEL SECURITY;

-- Create trigger to update the updated_at timestamp
CREATE OR REPLACE FUNCTION update_documents_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_documents_updated_at
BEFORE UPDATE ON documents
FOR EACH ROW
EXECUTE FUNCTION update_documents_updated_at();