FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir watchdog

# Copy the rest of your backend code
COPY . .

# Set environment variables
ENV FLASK_APP=server/app.py
ENV FLASK_DEBUG=1
ENV FLASK_ENV=development
ENV PYTHONUNBUFFERED=1

# Expose the port the app runs on
EXPOSE 5000

# Command to run the application with auto-reload
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"] 