"""Force add missing columns

Revision ID: 353ab7657820
Revises: 400a67d5474d
Create Date: 2025-02-08 20:47:10.589321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '353ab7657820'
down_revision = '400a67d5474d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('breeding_programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('breeding_programs', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('contact_email')

    # ### end Alembic commands ###
