"""Restoring DogBreed model

Revision ID: 67e7ed5b767b
Revises: 353ab7657820
Create Date: 2025-02-09 12:49:33.582881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e7ed5b767b'
down_revision = '353ab7657820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puppies')
    op.drop_table('breeder_program_association')
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('owner_id')
        batch_op.drop_column('registration_number')
        batch_op.drop_column('pedigree_info')
        batch_op.drop_column('microchip_number')
        batch_op.drop_column('awards')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('awards', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('microchip_number', sa.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('pedigree_info', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('registration_number', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])

    op.create_table('breeder_program_association',
    sa.Column('breeder_id', sa.INTEGER(), nullable=True),
    sa.Column('program_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['breeder_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['breeding_programs.id'], )
    )
    op.create_table('puppies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=6), nullable=False),
    sa.Column('litter_id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.ForeignKeyConstraint(['litter_id'], ['litters.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
