"""Initial database setup

Revision ID: c650ca65f0d6
Revises: 
Create Date: 2025-02-08 13:49:29.769598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c650ca65f0d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dog_breeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('coat_colors', sa.Text(), nullable=True),
    sa.Column('breed_type', sa.String(length=100), nullable=True),
    sa.Column('traits', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('breeding_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('facility_details', sa.Text(), nullable=True),
    sa.Column('testimonial', sa.Text(), nullable=True),
    sa.Column('breeder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['breeder_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registered_name', sa.String(length=100), nullable=False),
    sa.Column('call_name', sa.String(length=50), nullable=True),
    sa.Column('breed_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', name='gender_enum'), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('microchip_number', sa.String(length=30), nullable=True),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('breeder_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('Upcoming', 'Active', 'Retired', name='dog_status_enum'), nullable=False),
    sa.Column('awards', sa.Text(), nullable=True),
    sa.Column('pedigree_info', sa.Text(), nullable=True),
    sa.Column('cover_photo', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['breed_id'], ['dog_breeds.id'], ),
    sa.ForeignKeyConstraint(['breeder_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('microchip_number'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('breeder_program_association',
    sa.Column('breeder_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['breeder_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['breeding_programs.id'], )
    )
    op.create_table('dog_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('litters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('breed_id', sa.Integer(), nullable=True),
    sa.Column('sire_id', sa.Integer(), nullable=True),
    sa.Column('dam_id', sa.Integer(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('Expected', 'Planned', 'Current', name='litter_status_enum'), nullable=False),
    sa.Column('num_puppies', sa.Integer(), nullable=True),
    sa.Column('availability_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['breed_id'], ['dog_breeds.id'], ),
    sa.ForeignKeyConstraint(['dam_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['breeding_programs.id'], ),
    sa.ForeignKeyConstraint(['sire_id'], ['dogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('puppies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', name='gender_enum'), nullable=False),
    sa.Column('litter_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('Available', 'Reserved', 'Sold', name='puppy_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['litter_id'], ['litters.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('BUYER', 'BREEDER', 'ADMIN', name='userrole'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('BUYER', 'BREEDER', 'ADMIN', name='userrole'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('contact_number')
        batch_op.drop_column('location')

    op.drop_table('puppies')
    op.drop_table('litters')
    op.drop_table('dog_photos')
    op.drop_table('breeder_program_association')
    op.drop_table('dogs')
    op.drop_table('breeding_programs')
    op.drop_table('dog_breeds')
    # ### end Alembic commands ###
