"""Added ContactMessage model

Revision ID: 1239e1112d55
Revises: c650ca65f0d6
Create Date: 2025-02-08 19:28:44.445906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1239e1112d55'
down_revision = 'c650ca65f0d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('litters')
    op.drop_table('dog_breeds')
    op.drop_table('dog_photos')
    op.drop_table('dogs')
    op.drop_table('breeding_programs')
    op.drop_table('puppies')
    op.drop_table('breeder_program_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breeder_program_association',
    sa.Column('breeder_id', sa.INTEGER(), nullable=True),
    sa.Column('program_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['breeder_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['breeding_programs.id'], )
    )
    op.create_table('puppies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=6), nullable=False),
    sa.Column('litter_id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.ForeignKeyConstraint(['litter_id'], ['litters.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('breeding_programs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('facility_details', sa.TEXT(), nullable=True),
    sa.Column('testimonial', sa.TEXT(), nullable=True),
    sa.Column('breeder_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['breeder_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dogs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('registered_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('call_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('breed_id', sa.INTEGER(), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=6), nullable=False),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('microchip_number', sa.VARCHAR(length=30), nullable=True),
    sa.Column('registration_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.Column('breeder_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=8), nullable=False),
    sa.Column('awards', sa.TEXT(), nullable=True),
    sa.Column('pedigree_info', sa.TEXT(), nullable=True),
    sa.Column('cover_photo', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['breed_id'], ['dog_breeds.id'], ),
    sa.ForeignKeyConstraint(['breeder_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('microchip_number'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('dog_photos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dog_id', sa.INTEGER(), nullable=False),
    sa.Column('photo_url', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dog_breeds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), nullable=False),
    sa.Column('coat_colors', sa.TEXT(), nullable=True),
    sa.Column('breed_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('traits', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('litters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('program_id', sa.INTEGER(), nullable=True),
    sa.Column('breed_id', sa.INTEGER(), nullable=True),
    sa.Column('sire_id', sa.INTEGER(), nullable=True),
    sa.Column('dam_id', sa.INTEGER(), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=8), nullable=False),
    sa.Column('num_puppies', sa.INTEGER(), nullable=True),
    sa.Column('availability_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['breed_id'], ['dog_breeds.id'], ),
    sa.ForeignKeyConstraint(['dam_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['breeding_programs.id'], ),
    sa.ForeignKeyConstraint(['sire_id'], ['dogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('role', sa.VARCHAR(length=7), nullable=True),
    sa.Column('location', sa.VARCHAR(length=200), nullable=True),
    sa.Column('contact_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
